Python harmonic
astro-informatics/s2let pull request #44
Opened 2022-01-22 17:35 UTC by auggiemarignier

Carrying on from #22.  Python wrappers for the wavelet transforms and adjoints in harmonic space.  So far only had wrappers for the pixel space transforms.  This goes some way towards #20

2022-01-22 21:24 UTC, paddyroddy commented on src/test/python/test_directional_harmonic.py
> +    return np.random.default_rng(getattr(request.config.option, "randomly_seed", None))
Yay for new `numpy.random` 😄

2022-01-22 21:25 UTC, paddyroddy commented on src/test/python/test_directional_harmonic.py
> +)
noice, btw if you're not aware the library [hypothesis](https://hypothesis.readthedocs.io/en/latest/) is great for getting a test to run multiple circumstances

2022-01-22 21:26 UTC, paddyroddy commented on src/test/python/test_directional_harmonic.py
> +    px2wav, wav2px, rng: np.random.Generator, L=10, B=2, J_min=2
`nit`: would be great if typing was used everywhere 😉

2022-01-22 21:26 UTC, paddyroddy commented on src/test/python/test_directional_harmonic.py
> +    from pys2let import pys2let_j_max
this should really be at the top

2022-01-22 21:26 UTC, paddyroddy commented on src/test/python/test_directional_harmonic.py
> +    assert y_wav.conj().T @ x_wav + y_scal.conj() @ x_scal == approx(y.conj().T @ x)
could this be made more readable?

2022-01-22 21:27 UTC, paddyroddy requested changes
a few comments, otherwise good

2022-01-24 11:32 UTC, auggiemarignier commented on src/test/python/test_directional_harmonic.py
> +    from pys2let import pys2let_j_max
`1a81b64`

2022-01-24 11:33 UTC, auggiemarignier commented on src/test/python/test_directional_harmonic.py
> +    assert y_wav.conj().T @ x_wav + y_scal.conj() @ x_scal == approx(y.conj().T @ x)
`b185675`

2022-01-24 11:55 UTC, paddyroddy approved these changes
👍

2022-01-26 11:38 UTC, mdavezac approved these changes

2022-01-26 13:38 UTC, auggiemarignier commented
who has the authority to merge and deploy this? @mdavezac @jasonmcewen

2022-01-26 14:14 UTC, merged